import { ROLES } from './roles';

export const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'PERM_DASHBOARD_VIEW',
  CUSTOMER_VIEW: 'PERM_CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'PERM_CUSTOMER_CREATE',
  CUSTOMER_EDIT: 'PERM_CUSTOMER_EDIT',
  SUPPLIER_VIEW: 'PERM_SUPPLIER_VIEW',
  SUPPLIER_CREATE: 'PERM_SUPPLIER_CREATE',
  SUPPLIER_EDIT: 'PERM_SUPPLIER_EDIT',
  PRODUCT_FAMILY_VIEW: 'PERM_PRODUCT_FAMILY_VIEW',
  RFQ_VIEW: 'PERM_RFQ_VIEW',
  RFQ_CREATE: 'PERM_RFQ_CREATE',
  PRICE_INQUIRY_VIEW: 'PERM_PRICE_INQUIRY_VIEW',
  EMPLOYEE_VIEW: 'PERM_EMPLOYEE_VIEW',
  SYSTEM_CONFIG_VIEW: 'PERM_SYSTEM_CONFIG_VIEW',
  QUOTATION_VIEW: 'PERM_QUOTATION_VIEW',
  QUOTATION_CREATE: 'PERM_QUOTATION_CREATE',
  QUOTATION_EDIT: 'PERM_QUOTATION_CREATE',
  RECEIVE_PRODUCT_VIEW: 'PERM_RECEIVE_PRODUCT_VIEW',
  BUYING_PRODUCT_VIEW: 'PERM_BUYING_PRODUCT_VIEW',
  PURCHASE_ORDER_VIEW: 'PERM_PURCHASE_ORDER_VIEW',
  PURCHASE_ORDER_CREATE: 'PERM_PURCHASE_ORDER_CREATE',
  SALE_ORDER_VIEW: 'PERM_SALE_ORDER_VIEW',
  SALE_ORDER_CREATE: 'PERM_SALE_ORDER_CREATE',
  BILLING_VIEW: 'PERM_BILLING_VIEW',
  BILLING_CREATE: 'PERM_BILLING_CREATE',
  INVOICE_VIEW: 'PERM_INVOICE_VIEW',
  INVOICE_CREATE: 'PERM_INVOICE_CREATE',
  PRODUCT_VIEW: 'PERM_PRODUCT_VIEW',
  PRODUCT_PRICE_VIEW: 'PERM_PRODUCT_PRICE_VIEW',
  PRICE_LIST_VIEW: 'PERM_PRICE_LIST_VIEW',
  USER_MANAGE: 'PERM_USER_MANAGE',
  FREIGHT_VIEW: 'PERM_FREIGHT_VIEW',
  MANUAL_VIEW: 'PERM_MANUAL_VIEW',
  ACCOUNT_SETTING_VIEW: 'PERM_ACCOUNT_SETTING_VIEW'
});

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.PRODUCT_FAMILY_VIEW,
    PERMISSIONS.RFQ_VIEW,
    PERMISSIONS.RFQ_CREATE,
    PERMISSIONS.PRICE_INQUIRY_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.SALES]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RFQ_VIEW,
    PERMISSIONS.RFQ_CREATE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.SALES_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RFQ_VIEW,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.PROCUREMENT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RFQ_VIEW,
    PERMISSIONS.PRICE_INQUIRY_VIEW,
    PERMISSIONS.BUYING_PRODUCT_VIEW,
    PERMISSIONS.PURCHASE_ORDER_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.PROCUREMENT_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.BUYING_PRODUCT_VIEW,
    PERMISSIONS.PURCHASE_ORDER_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.RECEIVER]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.RECEIVE_PRODUCT_VIEW, PERMISSIONS.MANUAL_VIEW],
  [ROLES.RECEIVER_PAK_KLONG]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RECEIVE_PRODUCT_VIEW,
    PERMISSIONS.MANUAL_VIEW
  ],
  [ROLES.ADMIN_BKK]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.SALE_ORDER_CREATE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.ADMIN_PROVINCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.SALE_ORDER_CREATE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.ORDER_BKK]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.ORDER_PROVINCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.ACCOUNT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.PRODUCT_PRICE_VIEW,
    PERMISSIONS.FREIGHT_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ],
  [ROLES.ACCOUNT_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.PRODUCT_PRICE_VIEW,
    PERMISSIONS.FREIGHT_VIEW,
    PERMISSIONS.MANUAL_VIEW,
    PERMISSIONS.ACCOUNT_SETTING_VIEW
  ]
};

export const getRoleFallbackPermissions = (role?: string | null): string[] =>
  role ? DEFAULT_ROLE_PERMISSIONS[role] || [] : [];

export const mergePermissions = (role: string | null | undefined, permissions?: string[] | null) =>
  Array.from(new Set([...(permissions || []), ...getRoleFallbackPermissions(role)]));
