export const PRIVILEGES = Object.freeze({
  PERM_VOUCHER_EDIT: 'PERM_VOUCHER_EDIT',
  PERM_VOUCHER_CREATE: 'PERM_VOUCHER_CREATE',
  PERM_VOUCHER_VIEW: 'PERM_VOUCHER_VIEW',
  PERM_VOUCHER_CODE_VIEW: 'PERM_VOUCHER_CODE_VIEW',
  PERM_BOOKING_RENTAL_VIEW: 'PERM_BOOKING_RENTAL_VIEW',
  PERM_CAR_ACTIVITY_VIEW: 'PERM_CAR_ACTIVITY_VIEW',
  PERM_CAR_ACTIVITY_EDIT: 'PERM_CAR_ACTIVITY_EDIT',
  PERM_BOOKING_TYPE_VIEW: 'PERM_BOOKING_TYPE_VIEW',
  PERM_DOCUMENT_CONTENT_VIEW: 'PERM_DOCUMENT_CONTENT_VIEW',
  PERM_DOCUMENT_CONTENT_CREATE: 'PERM_DOCUMENT_CONTENT_CREATE',
  PERM_DOCUMENT_CONTENT_EDIT: 'PERM_DOCUMENT_CONTENT_EDIT',
  PERM_CUSTOMER_VIEW: 'PERM_CUSTOMER_VIEW',
  PERM_CUSTOMER_EDIT: 'PERM_CUSTOMER_EDIT',
  PERM_CUSTOMER_GROUP_CREATE: 'PERM_CUSTOMER_GROUP_CREATE',
  PERM_CUSTOMER_GROUP_VIEW: 'PERM_CUSTOMER_GROUP_VIEW',
  PERM_CUSTOMER_GROUP_EDIT: 'PERM_CUSTOMER_GROUP_EDIT',
  PERM_COOKIE_CONSENT_VIEW: 'PERM_COOKIE_CONSENT_VIEW',
  PERM_AGREEMENT_DOCUMENT_VIEW: 'PERM_AGREEMENT_DOCUMENT_VIEW',
  PERM_AGREEMENT_DOCUMENT_ACTIVE_VIEW: 'PERM_AGREEMENT_DOCUMENT_ACTIVE_VIEW',
  PERM_CAR_USABILITY_VIEW: 'PERM_CAR_USABILITY_VIEW',
  PERM_CAR_DETAIL_VIEW: 'PERM_CAR_DETAIL_VIEW',
  PERM_CAR_EDIT: 'PERM_CAR_EDIT',
  PERM_CAR_VIEW: 'PERM_CAR_VIEW',
  PERM_BOOKING_RESERVATION_CREATE: 'PERM_BOOKING_RESERVATION_CREATE',
  PERM_BOOKING_RESERVATION_DELETE: 'PERM_BOOKING_RESERVATION_DELETE',
  PERM_BOOKING_RESERVATION_EDIT: 'PERM_BOOKING_RESERVATION_EDIT',
  PERM_ADMIN_USER_CREATE: 'PERM_ADMIN_USER_CREATE',
  PERM_ADMIN_USER_VIEW: 'PERM_ADMIN_USER_VIEW',
  PERM_ADMIN_USER_OWN_PROFILE_VIEW: 'PERM_ADMIN_USER_OWN_PROFILE_VIEW',
  PERM_ACCOUNT_ACTIVATION_VIEW: 'PERM_ACCOUNT_ACTIVATION_VIEW',
  PERM_ACCOUNT_ACTIVATION_EDIT: 'PERM_ACCOUNT_ACTIVATION_EDIT',
  PERM_CAR_MODEL_EDIT: 'PERM_CAR_MODEL_EDIT',
  PERM_CAR_MODEL_VIEW: 'PERM_CAR_MODEL_VIEW',
  PERM_BOOKING_RENTAL_EDIT: 'PERM_BOOKING_RENTAL_EDIT',
  PERM_PACKAGE_PRICE_VIEW: 'PERM_PACKAGE_PRICE_VIEW',
  PERM_COOKIE_CONTENT_VIEW: 'PERM_COOKIE_CONTENT_VIEW',
  PERM_DASHBOARD_VIEW: 'PERM_DASHBOARD_VIEW',
  PERM_CAR_BRAND_VIEW: 'PERM_CAR_BRAND_VIEW',
  PERM_SUBSCRIPTION_PACKAGE_MANAGEMENT_LIST_VIEW: 'PERM_SUBSCRIPTION_PACKAGE_MANAGEMENT_LIST_VIEW',
  PERM_SUBSCRIPTION_PACKAGE_MANAGEMENT_DETAIL_CREATE:
    'PERM_SUBSCRIPTION_PACKAGE_MANAGEMENT_DETAIL_CREATE',
  PERM_ADMIN_USER_EDIT: 'PERM_ADMIN_USER_EDIT',
  PERM_NOT_PUBLISH: 'PERM_NOT_PUBLISH',
  PERM_COMMON_VIEW: 'PERM_COMMON_VIEW',
  PERM_LEAD_MANAGEMENT_VIEW: 'PERM_LEAD_MANAGEMENT_VIEW',
  PERM_LEAD_MANAGEMENT_EXPORT: 'PERM_LEAD_MANAGEMENT_EXPORT'
});

export type Privilege =
  | typeof PRIVILEGES.PERM_VOUCHER_EDIT
  | typeof PRIVILEGES.PERM_VOUCHER_CREATE
  | typeof PRIVILEGES.PERM_VOUCHER_VIEW
  | typeof PRIVILEGES.PERM_VOUCHER_CODE_VIEW
  | typeof PRIVILEGES.PERM_BOOKING_RENTAL_VIEW
  | typeof PRIVILEGES.PERM_CAR_ACTIVITY_VIEW
  | typeof PRIVILEGES.PERM_CAR_ACTIVITY_EDIT
  | typeof PRIVILEGES.PERM_BOOKING_TYPE_VIEW
  | typeof PRIVILEGES.PERM_DOCUMENT_CONTENT_VIEW
  | typeof PRIVILEGES.PERM_DOCUMENT_CONTENT_CREATE
  | typeof PRIVILEGES.PERM_DOCUMENT_CONTENT_EDIT
  | typeof PRIVILEGES.PERM_CUSTOMER_VIEW
  | typeof PRIVILEGES.PERM_CUSTOMER_EDIT
  | typeof PRIVILEGES.PERM_CUSTOMER_GROUP_CREATE
  | typeof PRIVILEGES.PERM_CUSTOMER_GROUP_VIEW
  | typeof PRIVILEGES.PERM_CUSTOMER_GROUP_EDIT
  | typeof PRIVILEGES.PERM_COOKIE_CONSENT_VIEW
  | typeof PRIVILEGES.PERM_AGREEMENT_DOCUMENT_VIEW
  | typeof PRIVILEGES.PERM_AGREEMENT_DOCUMENT_ACTIVE_VIEW
  | typeof PRIVILEGES.PERM_CAR_USABILITY_VIEW
  | typeof PRIVILEGES.PERM_CAR_DETAIL_VIEW
  | typeof PRIVILEGES.PERM_CAR_EDIT
  | typeof PRIVILEGES.PERM_CAR_VIEW
  | typeof PRIVILEGES.PERM_BOOKING_RESERVATION_CREATE
  | typeof PRIVILEGES.PERM_BOOKING_RESERVATION_DELETE
  | typeof PRIVILEGES.PERM_BOOKING_RESERVATION_EDIT
  | typeof PRIVILEGES.PERM_ADMIN_USER_CREATE
  | typeof PRIVILEGES.PERM_ADMIN_USER_VIEW
  | typeof PRIVILEGES.PERM_ADMIN_USER_OWN_PROFILE_VIEW
  | typeof PRIVILEGES.PERM_ACCOUNT_ACTIVATION_VIEW
  | typeof PRIVILEGES.PERM_ACCOUNT_ACTIVATION_EDIT
  | typeof PRIVILEGES.PERM_CAR_MODEL_EDIT
  | typeof PRIVILEGES.PERM_CAR_MODEL_VIEW
  | typeof PRIVILEGES.PERM_BOOKING_RENTAL_EDIT
  | typeof PRIVILEGES.PERM_PACKAGE_PRICE_VIEW
  | typeof PRIVILEGES.PERM_COOKIE_CONTENT_VIEW
  | typeof PRIVILEGES.PERM_DASHBOARD_VIEW
  | typeof PRIVILEGES.PERM_CAR_BRAND_VIEW
  | typeof PRIVILEGES.PERM_SUBSCRIPTION_PACKAGE_MANAGEMENT_LIST_VIEW
  | typeof PRIVILEGES.PERM_SUBSCRIPTION_PACKAGE_MANAGEMENT_DETAIL_CREATE
  | typeof PRIVILEGES.PERM_ADMIN_USER_EDIT
  | typeof PRIVILEGES.PERM_NOT_PUBLISH
  | typeof PRIVILEGES.PERM_COMMON_VIEW
  | typeof PRIVILEGES.PERM_LEAD_MANAGEMENT_VIEW
  | typeof PRIVILEGES.PERM_LEAD_MANAGEMENT_EXPORT;

export const hasAllowedPrivilege = (
  privileges?: string[] | null,
  allowedPrivileges?: Privilege[]
): boolean => {
  if (!allowedPrivileges || !allowedPrivileges.length) {
    return true;
  }

  const found: boolean | undefined = privileges?.some((p) => allowedPrivileges.includes(p));
  return found === undefined ? false : found;
};
